export const posts = [
    {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    },
    {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:true
    },{
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    },{
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    },
    {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    },
    {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    }, {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    }, {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    }, {
        brand:'Bmw',
        name:'Bmw M3',
        prize:'760',
        country:'Nigeria',
        city:'Lagos',
        specs:[],
        info:[],
        description:"",
        sold:false,
        imgs:[],
        banner:"",
        favourite:false
    },
]